
flexion30 = [featureExtractionMovVar(DF_EmgData30(start:ending,:)); ...
    featureExtractionMovVar(FF_EmgData30(start:ending,:)); ...
    featureExtractionMovVar(SF_EmgData30(start:ending,:))]

flexion50 = [featureExtractionMovVar(DF_EmgData50(start:ending,:)); ...
    featureExtractionMovVar(FF_EmgData50(start:ending,:)); ...
    featureExtractionMovVar(SF_EmgData50(start:ending,:))]

flexion80 = [featureExtractionMovVar(DF_EmgData80(start:ending,:)); ...
    featureExtractionMovVar(FF_EmgData80(start:ending,:)); ...
    featureExtractionMovVar(SF_EmgData80(start:ending,:))]

allF_Flexion = [flexion30; flexion50; flexion80];
save('allF_Flexion.mat','allF_Flexion');